# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
# (*, stars) are wildcards to match ay possible value
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    # this will trigger pipelines in master and any under releases folder
    - master
    - releases/*
    exclude:
    # This will exclude old releases
    - releases/old/*

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
