name: Build and deploy code to Dockerhub

on: [push, pull_request]

jobs:
  lint_python:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: lint python
        uses: py-actions/flake8@v2
        with:
          ignore: "E501"
          max-line-length: "100"
          path: "app"

  deploy:
    environment:
      name: http-proxy-secrets
    runs-on: ubuntu-latest
    needs: [lint_python]
    name: Deploy to Dockerhub
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/proxy-http:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/proxy-http:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/proxy-http:buildcache,mode=max